output:
  format: "json" # Maybe add option for pickle?
  dir: "./output/"
  file: "output.json"
warmup: True
warmup_options:
  requests: 3
  timeout_sec: 20
storage: # TODO
  type: local
dataset:
  file: "datasets/openorca_large_subset_011.jsonl"
  max_queries: 20
  min_input_tokens: 0
  max_input_tokens: 100
  max_output_tokens: 200
  max_sequence_tokens: 150
load_options:
  type: constant #Future options: loadgen, stair-step
  concurrency: 5
  duration: 20 # In seconds. Maybe in future support "100s" "10m", etc...
plugin: "openai_plugin"
plugin_options:
  #interface: "grpc" # Some plugins like caikit-nlp-client should support grpc/http
  use_tls: False # Use True if querying an SSL grpc endpoint over https
  streaming: False
  model_name: "/mnt/models/"
  host: https://test-model-lupanza-shadowbot-ai--runtime-int.apps.stc-ai-e1-dev.bpis.p1.openshiftapps.com #"route.to.host"
  port: 443
  endpoint: "/v1/chat/completions"
extra_metadata:
  replicas: 1
